name: flutter_application_akhir
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_onboarding_screen:
  google_nav_bar: ^5.0.6
  http: ^0.13.1
  fl_chart: ^0.55.2
  common_ui_toolkit: ^0.2.6
  google_fonts: ^3.0.1
  card_loading: ^0.2.2
  iconly: ^1.0.1
  shared_preferences: ^2.0.15
  sqflite: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - images/Frame.png
     - images/Image.png
     - images/Pattern.png
     - images/dark.png
     - images/region_dark.png
     - images/type_dark.png
     - images/centraljava.png
     - images/westjava.png
     - images/eastjava.png
     - images/bali.png
     - images/Illustration-02.png
     - images/Illustration-03.png
     - images/Illustration-05.png
     - images/brush.png

  fonts:
     - family: Raleway
       fonts:
         - asset: fonts/Raleway-Black.ttf
         - asset: fonts/Raleway-BlackItalic.ttf
         - asset: fonts/Raleway-Bold.ttf
         - asset: fonts/Raleway-ExtraBold.ttf
         
     - family: Black
       fonts:
         - asset: fonts/Black_Theory.otf
     - family: Novembah
       fonts:
         - asset: fonts/Hey_November.ttf



         