name: flutter_application_akhir
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  flappy_search_bar_ns: ^2.0.2
  http: ^0.13.1
  fl_chart: ^0.55.2
  common_ui_toolkit: ^0.2.6
  filter_list: ^1.0.2
  calendar_appbar: ^0.0.6
  pie_chart: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - images/ina.jpg
     - images/jpn.jpg
     - images/chn.jpg
     - images/italy.jpg
     - images/krn.jpg

  fonts:
     - family: BentonSans
       fonts:
         - asset: fonts/BentonSans-Black.otf
         - asset: fonts/BentonSans-Thin.otf