name: flutter_application_akhir
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  http: ^0.13.1
  fl_chart: ^0.55.2
  common_ui_toolkit: ^0.2.6
  flutter_timer_countdown: ^1.0.5
  d_chart: ^0.1.0
  cool_stepper: ^1.2.1
  google_fonts: ^3.0.1
  vertical_card_pager: ^1.5.0
  flappy_search_bar_ns: ^2.0.2
  flutter_image_slideshow: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - images/Frame.png
     - images/Image.png
     - images/Pattern.png
     - images/boil.jpg
     - images/saute.jpg
     - images/steam.jpg
     - images/deepfry.jpg
     - images/grill.jpg
     - images/brush.png
     - images/layer.png
     - images/dark.png

  fonts:
     - family: BentonSans
       fonts:
         - asset: fonts/BentonSans-Black.otf
         - asset: fonts/BentonSans-Thin.otf
     - family: HeyNov
       fonts:      
         - asset: fonts/Hey_November.ttf
     - family: Raleway
       fonts:      
         - asset: fonts/Raleway-Bold.ttf
    